version: '3.8'

services:
  scraper_launch:
    container_name: scraper
    build: .
    image: padopia-service:dev
    volumes:
    - .:/app
    depends_on:
    - rabbit

  rabbit:
    image: rabbitmq:3.8.3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
